### ISSUE TITLE
FC on sync - DecSyncCC v1.3.0

### ISSUE THREAD

**Issue by MaMiMa81** [39aldo39/DecSyncCC#36] opened 2020-07-23 14:49 UTC
Firstly thanks for this app - I use it with Syncthing between android & your Radicale-DecSync on my laptop with linux & from there its synced via Radicale to Calcurse.

My phone is antiquated Moto G (first gen) with a Lineage OS 14.1 based ROM (up to date).

Had been using using DecSyncCC since v1.2.0 without issue but this latest version (1.3.0) flags up a message to close the app. when it syncs of its own accord or whether I sync it manually. I've try to install several times, after reverting back to v1.2.3 each time (which is where I am now). One of the times I reinstalled it I thought I would re-sync to the database by un-checking & then re-checking the collections box but it ended up permently running so I had to Force Stop the app.
I notice this version is using kotlin, at least in part & I had been having issues on this phone with the latest release of the Transistor app by y20k [https://github.com/y20k/transistor/issues/274#issuecomment-656244775](url) which he has totally rewritten in kotlin - possible link ??

**Comment by 39aldo39** [comment] 2020-07-23 19:53
Thanks for the report, but unfortunately I couldn't reproduce the issue. I tried an emulator with the same Android version as your device, but it works fine. There also aren't significant changes on the sync logic between v1.2.3 and v1.3.0. There may be a problem in some library I use, so updating that may help. Kotlin shouldn't be the problem, it is just the programming language (v1.2.3 is also written in Kotlin and works just fine).

For further investigation, does the app still crash while syncing when:
- There are no collections enabled?
- You add a new empty collection and enable just that one?

**Comment by MaMiMa81** [comment] 2020-07-23 20:58
Good Evening
Thanks for the quick response.

- There are no collections enabled?
No crash

- You add a new empty collection and enable just that one?
Same - no crash - I even created an entry in Star calendar & synced & an event was created in the collection database.

So it would appear that it doesn't like my original collection for some reason. I had upgraded previously from v1.2.0 a couple of times till v1.2.3 without issue.
Something that is immediately apparent comparing the collection names - the name for my calendar collection is. ea75d4e4-5daf-c937-xxxx-xxxxxxxxxxxx (the x=characters) which is the collection name as supplied from Radicale. I kept it so because I'd had a couple of issue trying to sync on the Linux box - could that be an issue with this v1.3.0?

**Comment by 39aldo39** [comment] 2020-07-24 19:40
> So it would appear that it doesn't like my original collection for some reason.

Indeed, it looks like it. I suspect that the problem is in the ical4android library. There is even a recent commit that claims fixing a crash, but isn't in version 1.3.0.

I recommend staying on v1.2.3 for now and updating when a new version is released.

**Comment by MaMiMa81** [comment] 2020-07-24 21:32
OK - thanks for your response - I shall stay on v1.2.3 for the time being.
I am somewhat perplexed though because if the issue is due to the library as you suspect then surely other users would be affected?
During my 'update' attempts I even uninstalled v1.2.3 & then installed v1.3.0 however that I believe resulted in the creation of a new folder in all the sub folders (except new-entries) under the existing collection - see attached screenshot for example.
![DecSyncCC folder](https://user-images.githubusercontent.com/62703356/88437020-19b20480-cdf5-11ea-9c0a-77cb7f88dfe8.png)


It has synced across to the linux box but I assume its safe to delete all iterations of these new folders?

**Comment by 39aldo39** [comment] 2020-07-25 15:14
> I am somewhat perplexed though because if the issue is due to the library as you suspect then surely other users would be affected?

It doesn't have to be a widespread issue. As you already noted, creating a new collection doesn't give the same problem. It probably is some rare timezone/recurrence issue. The format for these files is very complex with a lot of exceptions, that's why I use a library for it.

> I assume though its safe to delete all iterations of these new folders?

Yes, those folders are created by v1.3.0 as it reworked the identifiers (#33). I am also working on an easier way to identify and delete unused folders.

**Comment by MaMiMa81** [comment] 2020-07-25 15:43
> It doesn't have to be a widespread issue. As you already noted, creating a new collection doesn't give the same problem. It probably is some rare timezone/recurrence issue. The format for these files is very complex with a lot of exceptions, that's why I use a library for it.

OK - thanks for your response again @39aldo39  - as I've stated I'll follow your advice & await a later release then.

**Comment by MaMiMa81** [comment] 2020-07-29 13:01
Good Afternoon
Updated to v1.4.0 just released through F-Droid but unfortunately the same issue persists
Regards

**Comment by py-crash** [comment] 2020-07-29 15:30
I can confirm. Version 1.3.0 and 1.4.0 will crash when trying to add a new event. Version 1.2.3 works

**Comment by 39aldo39** [comment] 2020-07-29 18:41
That is surprising. @py-crash does it crash for any event, or only particular ones?

Either one would be very useful:
- Can you figure out what events crash? So create a new collection and then start adding different kind of events with an immediate sync until one crashes.
- Try to get a log of the crash. For this you have to use 'logcat'. If you search for that you should be able to find a guide how to use it. But is not that straightforward to setup, as you need to install some debug tools on a computer etc. However, it would be very useful.

**Comment by py-crash** [comment] 2020-07-29 19:29
I will check out all the circumstances that cause the crash. 

Also found a [tutorial about logcat](https://www.youtube.com/watch?v=W6iDw76UpQw). I will install it and send the reports. Anything that I should check out or remove before sending them (I don't want private information leaking in a report)

**Comment by 39aldo39** [comment] 2020-07-29 19:33
You just need to send the crash, which should be like 20 lines in red. You can read those lines yourself, but will mostly contain line numbers in the source code and a small explanation of the crash.

**Comment by py-crash** [comment] 2020-07-29 22:13
# Crash1.txt
1. All the collections are updated since version 1.2.3 is installed.
2. Disable all collections (Calendars).
3. Upgrade the app with F-Droid to version 1.4.0.
4. Reable the collection. Application crashes. The message _DecSync has stop working_ appears.
5. The notification _Adding events of [collection name] keeps on the screen (even hours after the crash) and I need to force stop the app.

# Crash2.txt
1. Unistalled the app.
2. Install the version 1.4.0.
3. Create a new collection called _test_.
4. Create a new event called _test_.
5. Application crashes. The message _DecSync has stop working_ appears.

The same happens when the collections are synced, the app is upgraded and a new event is added.
[Crash1.txt](https://github.com/39aldo39/DecSyncCC/files/4997744/Crash1.txt)
[Crash2.txt](https://github.com/39aldo39/DecSyncCC/files/4997745/Crash2.txt)

**Comment by MaMiMa81** [comment] 2020-07-30 08:22
Good Morning
My experience is pretty similar to yours for the Crash 1 situation - here is my logcat for that:

[logcat_20200729.txt](https://github.com/39aldo39/DecSyncCC/files/4999843/logcat_20200729.txt)

Regarding the Crash 2 situation I didn't perform the requested by **39aldo39** task with v1.4.0:

> ..................
>     * Can you figure out what events crash? So create a new collection and then start adding different kind of events with an immediate sync until one crashes.
> ....................

However I did for v1.3.0 with somewhat different results - from above:


> .........................
>     * You add a new empty collection and enable just that one?
>       Same - no crash - I even created an entry in Etar calendar & synced & an event was created in the collection database.
> ....................

I've no logcat for this though.

**Comment by 39aldo39** [comment] 2020-07-30 18:02
Thank you for the logs, they were very helpful! I actually was able to reproduce the crash in an emulator. However, the first Android version I tried didn't show a popup of the crash, so I didn't notice it. But an even older version did show a popup. It actually doesn't crash on more recent versions of Android.

I managed to fix the crash!

**Comment by MaMiMa81** [comment] 2020-08-11 15:01
Updated to v1.4.1 as it was flagged as available on F-Droid.
Although you have incorporated your fix for this issue there are unfortunately problems for me:

- If I create an event in Calcurse on the laptop & sync to my phone it shows up in my calendar on the phone but if  

- If I create an event in my calendar on the phone, sync via DecSyncCC & Syncthing to my laptop the event synced correctly. However when I re-sync  DecsyncCC crashes & on restarting the app the event in my calendar on the phone gets deleted.

I tried uninstalling, rebooting & reinstalling DecsyncCC v1.4.1 but that resulting in a new folder in the existing collection being created as per my comment 11 above & when I tried to sync the collection it failed to show any events in my calendar app.

I attach a logcat after the app crash from when I had performed my initial upgrade of v1.4.1

[logcat_20200811.txt](https://github.com/39aldo39/DecSyncCC/files/5057667/logcat_20200811.txt)

**Comment by 39aldo39** [comment] 2020-08-14 12:24
I think this is a different issue, and unfortunately I can't reproduce it in an Emulator.

The logged error is very strange though, and I am not sure what is going on. It is also strange that the event gets deleted on the phone, it looks like your laptop does something weird. Is Calcurse the only application that uses DecSync on your laptop?

What I do get from the log is that the crash occurs when dealing with reminders. Could you test with an event with a reminder, and an event without?

**Comment by MaMiMa81** [comment] 2020-08-15 13:03
@39aldo39 

>  Is Calcurse the only application that uses DecSync on your laptop?

The process goes like this:

events synced with my collection in DecSync on the laptop via syncthing & which then outputs to the Radicale collection via Radicale DecSync - it is then synced by vdirsyncer to a 'database' (basically a 'collection' of .ics events) which then is synced by calcurse-vdir to the calcurse data file(s) - in my case only apts (appointments). A bit convoluted & data repeatative but it is the only way I was able to get it to work.
The vdirsyncer/calcurse-vdir combo is run by a very simple script calcurse-vdirsyncer.sh :

#!/bin/sh

calcurse-vdir -f -v export /home/mick/calendar/calcurse && \
	vdirsyncer sync yyyyyy/zzzzz && \
	calcurse-vdir -f -v import /home/mick/calendar/calcurse

That I have set up as a cronjob to run every 15 mins.
Syncthing is set to run every hour - both of these can be obviously over-ridden to run manually if required.

Manually running the script after syncthing has been running:

$ $HOME/.config/calcurse/calcurse-vdirsyncer.sh
Syncing yyyyyy/zzzzz
Copying (uploading) item fcb70417-34b7-4d57-8c45-2a5b9c376d64 to mick_calcurse/calcurse
Importing event /fcb70417-34b7-4d57-8c45-2a5b9c376d64 to calcurse


However when I run it again: 
$ $HOME/.config/calcurse/calcurse-vdirsyncer.sh
Deleting event /fcb70417-34b7-4d57-8c45-2a5b9c376d64
Writing event /1b94e522920c4b1df0f36ed0032efc3f83d69be3
Syncing yyyyyy/zzzzz
Copying (uploading) item 1b94e522920c4b1df0f36ed0032efc3f83d69be3 to mick_radicale/calendars-ea75d4e4-5daf-c937-431d-efaaaf31f3ed
Deleting item fcb70417-34b7-4d57-8c45-2a5b9c376d64 from mick_radicale/calendars-ea75d4e4-5daf-c937-431d-efaaaf31f3ed

The imported original event is changed & 'rebranded', the old original deleted (recursively upwards) & then the new rebranded 'original' is re-synced see attachments.


[1b94e522920c4b1df0f36ed0032efc3f83d69be3.txt](https://github.com/39aldo39/DecSyncCC/files/5078671/1b94e522920c4b1df0f36ed0032efc3f83d69be3.txt)
[fcb70417-34b7-4d57-8c45-2a5b9c376d64.txt](https://github.com/39aldo39/DecSyncCC/files/5078672/fcb70417-34b7-4d57-8c45-2a5b9c376d64.txt)



Calcurse is fairly limited with its features in some respects i.e. how reminders can be set -  only one & that is 5 mins before the event - but it is satisfactory for me.

The above is running v1.2.3 - I'll reinstall v.1.4.1 later & do what you ask then.

**Comment by 39aldo39** [comment] 2020-08-16 11:33
Thanks for the explanation!

As you say, your setup is a bit convoluted, but it should work. I am a bit surprised that it deletes an event and re-uploads it instead of updating it, but, again, it should work fine.

I was able to reproduce the issue with your event `1b94e522920c4b1df0f36ed0032efc3f83d69be3`! Note that I had to change the line `TRIGGER:-P300S` to `TRIGGER:-PT300S` to make it a valid ical. (The T isn't there for a duration measured in days or longer, maybe you changed it manually?)

I don't have time to investigate right now, but I least I can do it. I did note that it only crashed for Android 7.1 or lower. On Android 8 or higher it works fine.

**Comment by 39aldo39** [comment] 2020-08-18 19:49
I didn't manage to fix it yet, but I did some investigation. Just for reference: ical4android uses the function `Date.from`, which is added in Java 1.8 and is not available in Java 1.7, which leads to this crash. It is possible to fix this compatibility issue (https://developer.android.com/studio/write/java8-support). I have added all the requirements, but it still crashes...

**Comment by MaMiMa81** [comment] 2020-08-18 21:02
> I was able to reproduce the issue with your event 1b94e522920c4b1df0f36ed0032efc3f83d69be3! Note that I had to change the line TRIGGER:-P300S to TRIGGER:-PT300S to make it a valid ical. (The T isn't there for a duration measured in days or longer, maybe you changed it manually?)

No didn't change it manually - both events are exactly as produced from my syncing evolutions in my last post - apart from I had to rename both event files fro .ics to .txt to get them to be attached to that post.
In the original event from the phone the line is: TRIGGER:-PT5M

> I didn't manage to fix it yet, but I did some investigation. Just for reference: ical4android uses the function Date.from, which is added in Java 1.8 and is not available in Java 1.7, which leads to this crash. It is possible to fix this compatibility issue (https://developer.android.com/studio/write/java8-support). I have added all the requirements, but it still crashes...

In light of this do you need me to reinstall v.1.4.1 to:

> Could you test with an event with a reminder, and an event without?

**Comment by 39aldo39** [comment] 2020-08-27 18:59
I finally figured out why the desugaring didn't work. It is fixed now, there are no more crashes in my testing.

**Closed by 39aldo39** 2020-08-27 18:59 UTC

**Comment by MaMiMa81** [comment] 2020-09-01 09:29
> I finally figured out why the desugaring didn't work. It is fixed now, there are no more crashes in my testing.

Good Morning - v.1.4.2 just landed in the F-Droid repo & in light of what you state just above I duly installed it.
I thoroughly tested for my situation & indeed it working just as well as v.1.2.3 so thank you for that @39aldo39

**Comment by MaMiMa81** [comment] 2020-09-13 12:31
I've just been tinkering a bit with my setup:
Etar <> DecSynCC <> Syncthing <> Radicale-decsync <> Radicale <> vdirsyncer <> calcurse-vdir <> calcurse 

And referring back to your comment:
> .......................
It is also strange that the event gets deleted on the phone, it looks like your laptop does something weird.
...................

As you can see to my comments up above I run my calcurse-vdirsyncer.sh:

```
#!/bin/sh
calcurse-vdir -f -v export /home/mick/calendar/calcurse &&
vdirsyncer sync yyyyyy/zzzzz &&
calcurse-vdir -f -v import /home/mick/calendar/calcurse
```

 with calcurse-vdir set to the -f flag (force) - explained here in the calcurse-vdir README:

 

> **Usage**
> 
> calcurse-vdir requires an up-to-date version of calcurse and python. To run calcurse-vdir, call the script using
> 
> `calcurse-vdir <action> <vdir>`
> 
> where action is either import or export and where vdir is the local directory to interact with.
> 
> When importing events, calcurse-vdir imports every event found in the vdir directory that is not also present in calcurse. When exporting events, calcurse-vdir does the opposite and writes any new event to the vdir directory.
> 
> These operations are non-destructive by default, meaning that no event will be deleted by the script. The -f flag can be used to make the origin mirror the destination, potentially deleting events in the destination that are no longer present in the origin.

If I _don't_ have calcurse-vdir set to the -f flag the events get duplicated on _both_ calendars (Calcurse & Etar) - the original created event left unaltered.
But having the -f flag set _may_ be the reason for the event being deleted by calcurse & imported back into vdir 'database' ('collection' of .ics events) & then synced onwards.

This results in me having to make some, albeit minor, adjustments to my Etar entries sometimes - but I can live with that.

I hope this doesn't confuse matters my intention was to add some clarity lol.

**Comment by MahMoh-dev** [comment] 2022-01-22 12:04
@MaMiMa81 Could you please provide your vdirsyncer config? I'll really apreciate this as I'm trying to get calcurse sync with Etar but having a trouble with this specific part.
Thank you.

**Comment by MaMiMa81** [comment] 2022-02-08 03:17
Hello @MahMoh-dev

Firstly apologies for the late response but I have unfortunately been tucked up with some personal issues.

Regarding your question:
`~/.config/vdirsyncer/config
```
# An example configuration for vdirsyncer.
#
# Move it to ~/.vdirsyncer/config or ~/.config/vdirsyncer/config and edit it.
# Run `vdirsyncer --help` for CLI usage.
#
# Optional parameters are commented out.
# This file doesn't document all available parameters, see
# http://vdirsyncer.pimutils.org/ for the rest of them.

[general]
# A folder where vdirsyncer can store some metadata about each pair.
status_path = "~/.config/vdirsyncer/status/"

# CALDAV
[pair pepp_an]
a = "mick_apts"
b = "mick_rad_apts"
collections = null
conflict_resolution = "a wins"

# Calendars also have a color property
metadata = ["displayname", "color"]

[storage mick_apts]
type = "filesystem"
path = "~/calendar/calcurse/"
fileext = ".ics"

[storage mick_rad_apts]
type = "caldav"
url = "http://localhost:5232/mick/calendars-eeb6e200-f315-b0a1-4372-fbad5c001fd6/"`

```
Obviously your calendars collection in the url will be different.

To initially set up the sync connection you will need to run:

`vdirsyncer discover`

Then running:

`vdirsyncer sync`

Will sync the collection in the Radicale directory:

`~/.var/lib/radicale/collections/collection-root/mickcalendars-eeb6e200-f315-b0a1-4372-fbad5c001fd6/`
 
with the collection in the 'database' directory: 

`~/calendar/calcurse/`


This  'database' directory can then be synced with:

` ~/.local/calcurse/data/apts` 

file via `calcurse-vdir`

The whole sync process from the radicale collection to the apts file & back can be automated via the:`calcurse-vdirsyncer.sh`. I have altered the:

`calcurse-vdirsyncer.sh`

originally provided with calcurse (in the /contrib directory) to what is shown in the quote below (this is from a comment I made 16 comments above - PLEASE NOTE THOUGH I HAVE REMOVED THE 'yyyyyy/zzzzz' AFTER  `vdirsyncer sync` BECAUSE IT IS MISLEADING & I CANNOT RECALL WHAT MADE ME PUT IT IN IN THE FIRST PLACE! - IT CERTAINLY ISN'T IN MY CURRENT SCRIPT)

 
 

> The process goes like this:
>  
>  events synced with my collection in DecSync on the laptop via syncthing & which then outputs to the Radicale collection via Radicale DecSync - it is then synced by vdirsyncer to a 'database' (basically a 'collection' of .ics events) which then is synced by calcurse-vdir to the calcurse data file(s) - in my case only apts (appointments). A bit convoluted & data repeatative but it is the only way I was able to get it to work. The vdirsyncer/calcurse-vdir combo is run by a very simple script calcurse-vdirsyncer.sh :
>  
> ```
>  #!/bin/sh
>  calcurse-vdir -f -v export /home/mick/calendar/calcurse && vdirsyncer sync && calcurse-vdir -f -v import /home/mick/calendar/calcurse
> ```
>  
>  That I have set up as a cronjob to run every 15 mins. Syncthing is set to run every hour - both of these can be obviously over-ridden to run manually if required.
> ...................................

I have my Decsync set up now syncing my Tasks (Todo on calcurse <> OpenTasks Android) & Contacts too, which I access by Khard on my laptop. I can help you with their setup too if that interests you.

**Comment by MahMoh-dev** [comment] 2022-02-09 20:31
@MaMiMa81 Thank you so much, calendar and contacts collections are in sync with my phone right now.
However, I wasn't able to figure out the way you mentioned in the #47 issue to get calcurse todos syncing with Opentasks :(. I'm getting things done with (todo.txt + Simpletask) for now.

**Comment by MaMiMa81** [comment] 2022-02-10 16:09
@MahMoh-dev
Please see update to #47
